# Generated by Django 3.2.4 on 2021-06-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("link", models.URLField(max_length=250)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "amount_of_upvotes",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("author_name", models.CharField(max_length=60)),
            ],
        ),
    ]
